doc: How to create a devcontainer feature
daytonaio/content pull request #12
Opened 2024-08-19 15:01 UTC by varshith257

# Pull Request Template

## Writer's Checklist

- [ ] **Follow Writing Structure**
  - [ ] I have used more than two H2 subtitles to organize content.
  - [ ] Include an introduction with at least two paragraphs before the first H2 section.
  - [ ] Use bold, italic, underline, notes, quotes, TLDRs, and key points as needed.
  - [ ] Include `code elements` where appropriate.
  - [ ] Write the article in Markdown format.

- [ ] **Fact-Check**
  - [ ] I have verified all facts and data points included in the article.

- [ ] **Assets**
  - [ ] Save images in the `/assets` folder.
  - [ ] Follow naming conventions: `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.

- [ ] **Interlinking**
  - [ ] Use `CTRL+F` to search for relevant keywords on:
    - [Daytona Dotfiles Sitemap](https://www.daytona.io/sitemap-dotfiles.xml)
    - [Daytona Definitions Sitemap](https://www.daytona.io/sitemap-definitions.xml)
  - [ ] Interlink keywords using the appropriate URLs.

- [ ] **Glossary/Definitions**
  - [ ] Identify and mark new terms that could be added to the Definitions page.

- [ ] **Review and Edit**
  - [ ] Read the article out loud to catch any awkward phrasing.
  - [ ] Run the draft through [Grammarly](https://grammarly.com) or a similar tool to correct grammar and spelling errors.
  - [ ] Double-check adherence to the style guide and repository guidelines.

2024-08-19 15:03 UTC, varshith257 commented
@nkkko Any changes or improvements needed, I am happy to be incorporate them

2024-08-19 15:23 UTC, nkkko commented
Thank you. Could you please:
1. Have you tried if the feature works, as I haven't had time to test it? Please test it. And add the reference where people can find the full code.
2. Extend a bit introduction to explain why would anyone want to build a feature and why huggingface as example (a bit more elaboration to get people interested)
3. link the features list from microsoft and also add some more key references for writing features
4. add example of great and useful features
5. Fix errors.

2024-08-19 20:38 UTC, varshith257 commented
Yes, it is working. Here the logs of it :
```

Activating feature 'huggingface'
Python3 is already installed.
Using existing virtual environment at /opt/huggingface-venv.
Requirement already satisfied: pip in /opt/huggingface-venv/lib/python3.10/site-packages (24.2)
Requirement already satisfied: transformers in /opt/huggingface-venv/lib/python3.10/site-packages (4.44.0)
Requirement already satisfied: filelock in /opt/huggingface-venv/lib/python3.10/site-packages (from transformers) (3.15.4)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /opt/huggingface-venv/lib/python3.10/site-packages (from transformers) (0.24.6)
Requirement already satisfied: numpy>=1.17 in /opt/huggingface-venv/lib/python3.10/site-packages (from transformers) (2.1.0)
Requirement already satisfied: packaging>=20.0 in /opt/huggingface-venv/lib/python3.10/site-packages (from transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /opt/huggingface-venv/lib/python3.10/site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /opt/huggingface-venv/lib/python3.10/site-packages (from transformers) (2024.7.24)
Requirement already satisfied: requests in /opt/huggingface-venv/lib/python3.10/site-packages (from transformers) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in /opt/huggingface-venv/lib/python3.10/site-packages (from transformers) (0.4.4)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /opt/huggingface-venv/lib/python3.10/site-packages (from transformers) (0.19.1)
Requirement already satisfied: tqdm>=4.27 in /opt/huggingface-venv/lib/python3.10/site-packages (from transformers) (4.66.5)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/huggingface-venv/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (2024.6.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /opt/huggingface-venv/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/huggingface-venv/lib/python3.10/site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/huggingface-venv/lib/python3.10/site-packages (from requests->transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/huggingface-venv/lib/python3.10/site-packages (from requests->transformers) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /opt/huggingface-venv/lib/python3.10/site-packages (from requests->transformers) (2024.7.4)
Looking in indexes: https://download.pytorch.org/whl/cpu
Requirement already satisfied: torch in /opt/huggingface-venv/lib/python3.10/site-packages (2.4.0+cpu)
Requirement already satisfied: torchvision in /opt/huggingface-venv/lib/python3.10/site-packages (0.19.0+cpu)
Requirement already satisfied: torchaudio in /opt/huggingface-venv/lib/python3.10/site-packages (2.4.0+cpu)
Requirement already satisfied: filelock in /opt/huggingface-venv/lib/python3.10/site-packages (from torch) (3.15.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /opt/huggingface-venv/lib/python3.10/site-packages (from torch) (4.12.2)
Requirement already satisfied: sympy in /opt/huggingface-venv/lib/python3.10/site-packages (from torch) (1.12)
Requirement already satisfied: networkx in /opt/huggingface-venv/lib/python3.10/site-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in /opt/huggingface-venv/lib/python3.10/site-packages (from torch) (3.1.3)
Requirement already satisfied: fsspec in /opt/huggingface-venv/lib/python3.10/site-packages (from torch) (2024.6.1)
Requirement already satisfied: numpy in /opt/huggingface-venv/lib/python3.10/site-packages (from torchvision) (2.1.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /opt/huggingface-venv/lib/python3.10/site-packages (from torchvision) (10.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/huggingface-venv/lib/python3.10/site-packages (from jinja2->torch) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in /opt/huggingface-venv/lib/python3.10/site-packages (from sympy->torch) (1.3.0)
Collecting datasets
  Using cached datasets-2.21.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: filelock in /opt/huggingface-venv/lib/python3.10/site-packages (from datasets) (3.15.4)
Requirement already satisfied: numpy>=1.17 in /opt/huggingface-venv/lib/python3.10/site-packages (from datasets) (2.1.0)
Collecting pyarrow>=15.0.0 (from datasets)
  Using cached pyarrow-17.0.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Using cached dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Collecting pandas (from datasets)
  Using cached pandas-2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Requirement already satisfied: requests>=2.32.2 in /opt/huggingface-venv/lib/python3.10/site-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /opt/huggingface-venv/lib/python3.10/site-packages (from datasets) (4.66.5)
Collecting xxhash (from datasets)
  Using cached xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess (from datasets)
  Using cached multiprocess-0.70.16-py310-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec<=2024.6.1,>=2023.1.0 in /opt/huggingface-venv/lib/python3.10/site-packages (from fsspec[http]<=2024.6.1,>=2023.1.0->datasets) (2024.6.1)
Collecting aiohttp (from datasets)
  Using cached aiohttp-3.10.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.5 kB)
Requirement already satisfied: huggingface-hub>=0.21.2 in /opt/huggingface-venv/lib/python3.10/site-packages (from datasets) (0.24.6)
Requirement already satisfied: packaging in /opt/huggingface-venv/lib/python3.10/site-packages (from datasets) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /opt/huggingface-venv/lib/python3.10/site-packages (from datasets) (6.0.2)
Collecting aiohappyeyeballs>=2.3.0 (from aiohttp->datasets)
  Using cached aiohappyeyeballs-2.4.0-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.1.2 (from aiohttp->datasets)
  Using cached aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB)
Collecting attrs>=17.3.0 (from aiohttp->datasets)
  Using cached attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
Collecting frozenlist>=1.1.1 (from aiohttp->datasets)
  Using cached frozenlist-1.4.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp->datasets)
  Using cached multidict-6.0.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp->datasets)
  Using cached yarl-1.9.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (31 kB)
Collecting async-timeout<5.0,>=4.0 (from aiohttp->datasets)
  Using cached async_timeout-4.0.3-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /opt/huggingface-venv/lib/python3.10/site-packages (from huggingface-hub>=0.21.2->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/huggingface-venv/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/huggingface-venv/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/huggingface-venv/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /opt/huggingface-venv/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (2024.7.4)
Collecting python-dateutil>=2.8.2 (from pandas->datasets)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas->datasets)
  [...]

2024-08-19 22:09 UTC, varshith257 commented on guides/20240820_guide_template copy.md
> +Inside the `src` directory of your forked repository, create a new folder named `huggingface`. This folder will contain all the necessary configuration files and scripts for the Hugging Face feature.
A self-review for myself:

Can be added devcontainer cli installation cd and as well as a file structure of how devcontainer expects ?

Something like this"
```
├── src/
│   ├── huggingface/
│   │   ├── devcontainer-feature.json
│   │   ├── install.sh
│   │   ├── test/
│   │   │   └── test.sh
```

2024-08-19 22:09 UTC, varshith257 commented on guides/20240820_guide_template copy.md
> +
Add an example test script too.

2024-08-22 14:29 UTC, nkkko commented on authors/vamshi_maskuri.md
> +Author Image: ![vamshi-maskuri](profilr_photo.jpg)
fix

2024-08-22 14:29 UTC, nkkko commented on definitions/20240820_defintion_python.md
> +### Use in Daytona:
remove

2024-08-22 14:30 UTC, nkkko commented on guides/20240820_guide_devcontainer_feature.md
> +Devcontainer features are essential for standardizing development environments across various teams and projects. They allow developers to easily share and reuse environment setups, ensuring consiste
see checklist- at least 2 para

2024-08-22 14:33 UTC, nkkko commented on guides/20240820_guide_devcontainer_feature.md
> +Creating a Devcontainer feature is essential for teams that need to ensure a consistent development environment across different projects. It allows developers to quickly spin up environments that ar
wrong:
- "Devcontainer ~~feature~~ is essential for teams that need to ensure a consistent development environment "
- Development Container Features are self-contained, shareable units of installation code and development container configuration.

please read more about FEATURES!

2024-08-22 14:33 UTC, nkkko commented on guides/20240820_guide_devcontainer_feature.md
> +o follow along with this guide, you should have a basic understanding of[Python](definitions\20240820_defintion_python.md), [shell scripting](definitions\20240820_definition_shell_scripting.md) and [
fix?

2024-08-22 14:34 UTC, nkkko commented on guides/20240820_guide_devcontainer_feature.md
> +### TL;DR
tldr should summarise article and not steps like you wrote - please check older articles on the blog for examples

2024-08-22 14:35 UTC, nkkko commented on guides/20240820_guide_devcontainer_feature.md
> +## Common Issues and Troubleshooting
remove

2024-08-22 14:35 UTC, nkkko commented on guides/20240820_guide_devcontainer_feature.md
> +
extend a bit conclusion to 3 paragraphs, summarise key learnings etc.

2024-08-24 04:44 UTC, varshith257 commented on guides/20240820_guide_devcontainer_feature.md
> +devcontainer features test -f huggingface -i mcr.microsoft.com/devcontainers/base:ubuntu .
@nkkko Can I add a basic test to check their versions? Because I have seen this cd expects tests dir ?

2024-08-24 04:45 UTC, varshith257 commented
Related PR:
- https://github.com/nkkko/features/pull/1

2024-08-27 06:02 UTC, varshith257 commented
@nkkko Can you have review on upstream PR and here at your free time?

2024-08-31 12:57 UTC, varshith257 commented
@nkkko Can have a review on it? I will make changes if any needed 😄

2024-08-31 15:05 UTC, nkkko requested changes
do the changes and this can be considered done, thanks

2024-08-31 15:05 UTC, nkkko commented on guides/20240820_guide_devcontainer_feature.md
> +## Common Issues and Troubleshooting
you havent removed this section?

2024-08-31 16:08 UTC, varshith257 commented on guides/20240820_guide_devcontainer_feature.md
> +devcontainer features test -f huggingface -i mcr.microsoft.com/devcontainers/base:ubuntu .
Added

2024-08-31 16:16 UTC, varshith257 commented on README.md
Done!

2024-08-31 16:19 UTC, varshith257 commented on guides/20240820_guide_devcontainer_feature.md
> +## Common Issues and Troubleshooting
Done!

2024-09-01 21:41 UTC, nkkko approved these changes

2024-09-01 21:50 UTC, merged