feat: phi-3 and .NET integration with daytona
daytonaio/content pull request #135
Opened 2024-12-19 09:33 UTC by oreoluwa212

## Writer's Checklist
/claim #49 
[Starter Repository](https://github.com/oreoluwa212/phi-3_devcontainer)
### Writing Structure

- [x] Use short sentences and paragraphs, and include bucket brigades.
- [x] Include more than two descriptive H2 headings to organize content.
- [x] Capitalize headings according to the AP Stylebook
      ([use this tool](https://capitalizemytitle.com/style/AP/))
- [x] Include an introduction with at least two paragraphs before the first H2
      section.
- [x] Use appropriate formatting (bold, italic, underline), notes, quotes,
      TLDRs, and key points.
- [x] Incorporate `code elements` and `Markdown format` where appropriate.
- [x] Ensure at least one visual element per “screen” of the article
      (screenshots, diagrams, tables, graphs, lists, sidenotes, blockquotes).

### Fact-Checking

- [x] Verify all facts and data points included in the article.

### Asset Management

- [x] Save images in the `/assets` folder.
- [x] Follow naming conventions:
      `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.
- [x] (Optional) Create a GitHub repo for the code referenced in the article and
      share it.
- [ ] (Optional) Include a link to this Loom video in the PR comments.

### Interlinking

- [x] Use `CTRL+F` to search for relevant keywords in:
  - [Daytona Dotfiles Sitemap](https://www.daytona.io/sitemap-dotfiles.xml)
  - [Daytona Definitions Sitemap](https://www.daytona.io/sitemap-definitions.xml)
- [x] Interlink keywords using the appropriate URLs.

### Glossary/Definitions

- [x] Create new definition in `/defitnitions` folder.

### Review and Edit

- [x] Ensure articles address the needs of the target audience and their search
      intent.
- [x] Read the article out loud to catch any awkward phrasing.
- [x] Run the draft through [Grammarly](https://grammarly.com) or a similar
      grammar tool.
- [x] Double-check adherence to the style guide and repository guidelines.
- [x] Use the name of the article for the title of the PR.

2024-12-19 09:36 UTC, oreoluwa212 commented
@mojafa PR is ready for your review. thank.

2024-12-30 09:15 UTC, mojafa reviewed
@oreoluwa212 please make thiis changes

2024-12-30 09:17 UTC, mojafa commented on articles/20241219_Using_Phi-3_and_dot_NET_Development_in_Daytona.md
> +1. **Execute the Sample Project**: Navigate to your project directory and run the sample project:
Equally, I can't seem to open the project in remote container on my vscode. Looks like there's an issue with the `dotnet restore` command. Docker needs to see .NET project files (.csproj or .sln) at dotnet restore time.

do you have this on your end?

<img width="758" alt="Screenshot 2024-12-30 at 12 15 26" src="https://github.com/user-attachments/assets/a8b85d74-647a-4bd4-b83d-0cc645394b0b" />

2024-12-30 14:12 UTC, oreoluwa212 commented on articles/20241219_Using_Phi-3_and_dot_NET_Development_in_Daytona.md
> +1. **Execute the Sample Project**: Navigate to your project directory and run the sample project:
hi @mojafa apologies on the oversight
Kindly check now, I have made these changes

2024-12-30 14:18 UTC, oreoluwa212 commented on articles/20241219_Using_Phi-3_and_dot_NET_Development_in_Daytona.md
> +1. **Execute the Sample Project**: Navigate to your project directory and run the sample project:
the sample folder was also included in the root of the repository

2025-01-01 10:54 UTC, mojafa commented
@oreoluwa212  I  think we can do a little more. You've added so many screenshots... may be use them on need basis or showing expected final output. no need for the screenshots on the initializing daytona section. 


some sections need like a one or two sentences before the subsection heading or commands. 
<img width="958" alt="Screenshot 2025-01-01 at 13 44 41" src="https://github.com/user-attachments/assets/9c359943-ed59-4dd7-8a9f-e17238228fda" />

2025-01-01 10:55 UTC, mojafa commented
Please use this as a guide: https://github.com/daytonaio/content/blob/main/articles/20241212_Prebuilds_in_Daytona.md

2025-01-09 04:11 UTC, mojafa requested changes
@oreoluwa212 please fix this.

2025-01-09 17:42 UTC, oreoluwa212 commented on articles/20241219_Using_Phi-3_and_dot_NET_Development_in_Daytona.md
> +   ![Daytona Create RepoUrl](assets/20241224_Daytona_create_repo_url3.jpg)
done

2025-01-09 17:42 UTC, oreoluwa212 commented on articles/20241219_Using_Phi-3_and_dot_NET_Development_in_Daytona.md
> +6. **Configure your project file by creating, e.g `Phi3Sample.csproj` in the `Samples` directory:**
done

2025-01-09 17:42 UTC, oreoluwa212 commented
> @oreoluwa212 please fix this.

fixed

2025-01-20 15:25 UTC, mojafa requested changes
@oreoluwa212 Please fix this

2025-01-20 15:25 UTC, mojafa commented on articles/20241219_Using_Phi-3_and_dot_NET_Development_in_Daytona.md
> +3. **Configure your project file by creating a `Phi3Sample.csproj` file and adding the following script:**
@oreoluwa212 please follow a similar approach as above where you `md samples` then `cd samples` and `touch Phi3Sample.csproj`

2025-01-20 15:25 UTC, mojafa commented on articles/20241219_Using_Phi-3_and_dot_NET_Development_in_Daytona.md
> +### 3. Launch Daytona Environment
@oreoluwa212 I believe there's a step to push to github and whathot befire daytona.

2025-01-20 15:33 UTC, mojafa commented
also i still can't create the workspace when i run `daytona create my-repo-url` ....`daytona create https://github.com/mojafa/phi3-sampl.git`
try it on your end as well. 

i believe you need to check your devconatiner.json file and Dockerfile. Please test on your end

2025-01-21 11:23 UTC, oreoluwa212 commented
> also i still can't create the workspace when i run `daytona create my-repo-url` ....`daytona create https://github.com/mojafa/phi3-sampl.git` try it on your end as well.
> 
> i believe you need to check your devconatiner.json file and Dockerfile. Please test on your end

Apologies. a fix has been implemented and tested. Kindly try again.

2025-01-21 11:24 UTC, oreoluwa212 commented on articles/20241219_Using_Phi-3_and_dot_NET_Development_in_Daytona.md
> +### 3. Launch Daytona Environment
@mojafa i added the steps to push to github now

2025-01-21 11:24 UTC, oreoluwa212 commented on articles/20241219_Using_Phi-3_and_dot_NET_Development_in_Daytona.md
> +3. **Configure your project file by creating a `Phi3Sample.csproj` file and adding the following script:**
@mojafa done

2025-01-29 03:52 UTC, mojafa commented
@oreoluwa212 found the issue is docker-in-docker line in the devcontainer, as well as some missing packages in Dockerfile.

I've tested local dev container, and also usd the`daytona create` command as well.

<img width="1512" alt="Screenshot 2025-01-29 at 06 49 59" src="https://github.com/user-attachments/assets/834043bf-79da-4918-8dc6-5e07a72ec6e2" />

2025-01-29 04:58 UTC, oreoluwa212 commented
> @oreoluwa212 found the issue is docker-in-docker line in the devcontainer, as well as some missing packages in Dockerfile.
> 
> I've tested local dev container, and also usd the`daytona create` command as well.
> 
> <img alt="Screenshot 2025-01-29 at 06 49 59" width="1512" src="https://private-user-images.githubusercontent.com/38430072/407598828-834043bf-79da-4918-8dc6-5e07a72ec6e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgxMjUxNjEsIm5iZiI6MTczODEyNDg2MSwicGF0aCI6Ii8zODQzMDA3Mi80MDc1OTg4MjgtODM0MDQzYmYtNzlkYS00OTE4LThkYzYtNWUwN2E3MmVjNmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTI5VDA0Mjc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMTBjM2UxODRkNDRhNGMyMWMzYWYxNDQ2YjE3ZDllZTRiN2UzODNmMjliYmFiNmE1MTBmNGIzYTdkMGY4NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Iv4B6olhYcXASC-KXM9bEEWgDe0y2v147dMlDaN7XSk">

thank you for your guidance althrough

2025-01-31 12:22 UTC, mojafa commented
@oreoluwa212  Seen your other PR was closed; not sure how you managed to get two PRs open. But anyway, thanks for your contribution and discussion on this issue! We're doing some cleanup to keep the repo focused, and we've closed the issue this PR addresses for now. Appreciate your support! 🙏

2025-01-31 12:22 UTC, closed without merging

2025-01-31 12:51 UTC, oreoluwa212 commented
ok, duly noted