feat(article): add containerized development overview
daytonaio/content pull request #14
Opened 2024-08-19 16:22 UTC by onyedikachi-david

# Pull Request Template

## Writer's Checklist

- [x] **Follow Writing Structure**
  - [x] I have used more than two H2 subtitles to organize content.
  - [x] Include an introduction with at least two paragraphs before the first H2 section.
  - [x] Use bold, italic, underline, notes, quotes, TLDRs, and key points as needed.
  - [x] Include `code elements` where appropriate.
  - [x] Write the article in Markdown format.

- [ ] **Fact-Check**
  - [x] I have verified all facts and data points included in the article.

- [ ] **Assets**
  - [ ] Save images in the `/assets` folder.
  - [x] Follow naming conventions: `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.

- [ ] **Interlinking**
  - [ ] Use `CTRL+F` to search for relevant keywords on:
    - [Daytona Dotfiles Sitemap](https://www.daytona.io/sitemap-dotfiles.xml)
    - [Daytona Definitions Sitemap](https://www.daytona.io/sitemap-definitions.xml)
  - [ ] Interlink keywords using the appropriate URLs.

- [ ] **Glossary/Definitions**
  - [ ] Identify and mark new terms that could be added to the Definitions page.

- [ ] **Review and Edit**
  - [ ] Read the article out loud to catch any awkward phrasing.
  - [ ] Run the draft through [Grammarly](https://grammarly.com) or a similar tool to correct grammar and spelling errors.
  - [ ] Double-check adherence to the style guide and repository guidelines.

2024-08-20 10:47 UTC, nkkko reviewed
It has missed the point of the task "Dev Containers Vs. Traditional"
Checklist is not followed on all points, e.g. interlinking...

Content is of low quality 2/10.

2024-08-20 10:47 UTC, nkkko commented on articles/20240819_containerized_development.md
> +In the world of software development, consistency and reproducibility are paramount. Yet, developers often face the frustrating "it works on my machine" syndrome, where code behaves differently acros
Low effort content with obvious AI generated phrases and low value is not acceptable, such as:
- In the world of software development,
- emerged as a game-changing

2024-08-22 14:40 UTC, nkkko requested changes
please improve the article, thanks

2024-08-22 14:40 UTC, nkkko commented on README.md
@onyedikachi-david please remove readme from this PR

2024-08-22 15:05 UTC, onyedikachi-david commented on README.md
The readme file was added when I rebased to fix the unsigned previous commits.

I'll see how I can remove it.

2024-08-22 15:13 UTC, onyedikachi-david commented
> please improve the article, thanks

The latest contribution guide/instruction said that contributors are allowed one article per time till it's merged or closed, also someone else was assigned to this issue, so I decided to focus on the one assigned to me; that is, issue #9

2024-12-02 13:54 UTC, closed without merging