Feat:Added the article on application of containerization development
daytonaio/content pull request #18
Opened 2024-08-19 18:25 UTC by Mubashirshariq

# Pull Request Template
/claim #17 
/closed #17 

## Writer's Checklist

- [ ] **Follow Writing Structure**
  - [ ] I have used more than two H2 subtitles to organize content.
  - [ ] Include an introduction with at least two paragraphs before the first H2 section.
  - [ ] Use bold, italic, underline, notes, quotes, TLDRs, and key points as needed.
  - [ ] Include `code elements` where appropriate.
  - [ ] Write the article in Markdown format.

- [ ] **Fact-Check**
  - [ ] I have verified all facts and data points included in the article.

- [ ] **Assets**
  - [ ] Save images in the `/assets` folder.
  - [ ] Follow naming conventions: `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.

- [ ] **Interlinking**
  - [ ] Use `CTRL+F` to search for relevant keywords on:
    - [Daytona Dotfiles Sitemap](https://www.daytona.io/sitemap-dotfiles.xml)
    - [Daytona Definitions Sitemap](https://www.daytona.io/sitemap-definitions.xml)
  - [ ] Interlink keywords using the appropriate URLs.

- [ ] **Glossary/Definitions**
  - [ ] Identify and mark new terms that could be added to the Definitions page.

- [ ] **Review and Edit**
  - [ ] Read the article out loud to catch any awkward phrasing.
  - [ ] Run the draft through [Grammarly](https://grammarly.com) or a similar tool to correct grammar and spelling errors.
  - [ ] Double-check adherence to the style guide and repository guidelines.

2024-08-20 11:23 UTC, nkkko commented
I can't review until you implement the checklist and DCO.

2024-08-22 15:26 UTC, nkkko requested changes
article is a hot mess, but you could do something out of it.... please invest more time!!!! thanks

2024-08-22 15:26 UTC, nkkko commented on articles/20240819.md
> +**About The Warehouse Group**
when using content from others, in this case Docker case study, you should do it properly, reference docker source and write it as such... as evident from the case study done by Docker The Warehous .... has ...what... why... how

2024-08-22 15:26 UTC, nkkko commented on articles/20240819.md
> +---
what is this?

2024-08-22 15:26 UTC, nkkko commented on articles/20240819.md
> +### Download Case Study
this is messy

2024-08-22 15:26 UTC, nkkko commented on articles/20240819.md
> +- **Application Portability:** Containers package applications and their dependencies together, ensuring they run consistently across different environments and platforms, enhancing portability.
this is hard to read, the following h3 sections

2024-08-22 15:26 UTC, nkkko commented on articles/20240819.md
> +### Code Example
why this now?

2024-08-23 05:57 UTC, Mubashirshariq commented
@nkkko  I have made the required changes,plz review ,Thanks!

2024-09-10 09:50 UTC, nkkko commented
This is better but needs more work, please answer to all my comments to make it easier for me to understand what you did. Also you haven't add reference to the mention case study, and that case study is half of the article. Please reduce it and invest more effort. THanks

2024-12-02 13:25 UTC, mojafa commented
@Mubashirshariq there's quite a lot to be done. 

first off your article fails to address the issue: https://github.com/daytonaio/content/issues/7

> Insights into team workflows, onboarding processes, and long-term benefits.

also there's a lot of unneccessary spacing and linting issues. 

Please redo it and check the [CONTRIBUTING.md](https://github.com/daytonaio/content/blob/main/CONTRIBUTING.md) file and resubmit your article. Be sure toinclude image assets and refrences, as well as rename the article title.

2024-12-22 21:34 UTC, mojafa commented
@Mubashirshariq  any updates?

2024-12-30 11:45 UTC, mojafa commented
@Mubashirshariq any updates?

2025-01-31 12:12 UTC, closed without merging

2025-01-31 12:12 UTC, mojafa commented
@Mubashirshariq Thanks for your contribution and discussion on this issue! We're doing some cleanup to keep the repo focused, and we've closed the issue this PR addresses for now. Appreciate your support! 🙏