Gpu utilization
daytonaio/content pull request #25
Opened 2024-08-20 00:37 UTC by JohnnieJnr

/claim https://github.com/daytonaio/content/issues/8
/closed https://github.com/daytonaio/content/issues/8

# Pull Request Template

## Writer's Checklist

- [ ] **Follow Writing Structure**
  - [ ] I have used more than two H2 subtitles to organize content.
  - [ ] Include an introduction with at least two paragraphs before the first H2 section.
  - [ ] Use bold, italic, underline, notes, quotes, TLDRs, and key points as needed.
  - [ ] Include `code elements` where appropriate.
  - [ ] Write the article in Markdown format.

- [ ] **Fact-Check**
  - [ ] I have verified all facts and data points included in the article.

- [ ] **Assets**
  - [ ] Save images in the `/assets` folder.
  - [ ] Follow naming conventions: `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.

- [ ] **Interlinking**
  - [ ] Use `CTRL+F` to search for relevant keywords on:
    - [Daytona Dotfiles Sitemap](https://www.daytona.io/sitemap-dotfiles.xml)
    - [Daytona Definitions Sitemap](https://www.daytona.io/sitemap-definitions.xml)
  - [ ] Interlink keywords using the appropriate URLs.

- [ ] **Glossary/Definitions**
  - [ ] Identify and mark new terms that could be added to the Definitions page.

- [ ] **Review and Edit**
  - [ ] Read the article out loud to catch any awkward phrasing.
  - [ ] Run the draft through [Grammarly](https://grammarly.com) or a similar tool to correct grammar and spelling errors.
  - [ ] Double-check adherence to the style guide and repository guidelines.

2024-08-20 11:25 UTC, nkkko commented
I can't review until you implement the checklist.

2024-08-20 15:09 UTC, JohnnieJnr commented
I'm sorry for making your work difficult. I thought the checklist was to be used by you in your review hence the reason I ignored it. I'm making the necessary corrections now.

2024-08-22 15:45 UTC, nkkko requested changes
Have you tested this?

This is 5/10. 

Some serious errors, especially regarding Daytona. User need to be able to use the code and run it.

Share the code on your github repo, create a starter-gpu repo with all needed files to create a GPU enabled workspace in Daytona

2024-08-22 15:45 UTC, nkkko commented on articles/20240820_gpu_utilisation.md
> +
When using Daytona, daytona is cloning the repo adn creating workspace out of it inside the docker container

2024-08-22 15:45 UTC, nkkko commented on articles/20240820_gpu_utilisation.md
> +
where devcontainer? please add

2024-08-22 15:45 UTC, nkkko commented on articles/20240820_gpu_utilisation.md
> +   daytona run --gpus all nanogpt-gpu
this is halucination?!

2024-11-13 18:54 UTC, mojafa commented
@JohnnieJnr is this true?
#### Running nanoGPT in Daytona

Daytona is a container orchestration platform that simplifies running containerized applications, especially those requiring GPU support. To run nanoGPT in Daytona, follow these steps:

2024-11-13 18:55 UTC, mojafa commented
Please close this PR and fix all the changes. 
Create a new PR that matches the name of the issue:
`GPU Utilization in Containerized Environments`

2024-12-02 13:57 UTC, nkkko commented
@JohnnieJnr where are we with this?

2024-12-08 18:41 UTC, mojafa commented
@JohnnieJnr you have attempted 2 other issues and have 2 other open PRs.

2024-12-21 20:10 UTC, closed without merging