docs(1): thoughless oss always dies
daytonaio/content pull request #39
Opened 2024-08-20 20:21 UTC by hunxjunedo

fixes #1
/claim #1 

this article is written with high effort:
- contains case study to gradually build a conclusion for the reader
- has links of relevant articles and blogs to support the points
- has comparisons to stress on the facts
- has been written with careful consideration of the target audience, ensuring it's engaging for them

**therefore I'd like to get assigned, I'm working on adding media and illustration**

# Pull Request Template

## Writer's Checklist

- [ ] **Follow Writing Structure**
  - [x] I have used more than two H2 subtitles to organize content.
  - [x] Include an introduction with at least two paragraphs before the first H2 section.
  - [x] Use bold, italic, underline, notes, quotes, TLDRs, and key points as needed.
  - [ ] Include `code elements` where appropriate.
  - [x] Write the article in Markdown format.

- [x] **Fact-Check**
  - [x] I have verified all facts and data points included in the article.

- [ ] **Assets**
  - [ ] Save images in the `/assets` folder.
  - [ ] Follow naming conventions: `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.

- [ ] **Interlinking**
  - [ ] Use `CTRL+F` to search for relevant keywords on:
    - [Daytona Dotfiles Sitemap](https://www.daytona.io/sitemap-dotfiles.xml)
    - [Daytona Definitions Sitemap](https://www.daytona.io/sitemap-definitions.xml)
  - [x] Interlink keywords using the appropriate URLs.

- [ ] **Glossary/Definitions**
  - [ ] Identify and mark new terms that could be added to the Definitions page.

- [x] **Review and Edit**
  - [x] Read the article out loud to catch any awkward phrasing.
  - [x] Run the draft through [Grammarly](https://grammarly.com) or a similar tool to correct grammar and spelling errors.
  - [x] Double-check adherence to the style guide and repository guidelines.

2024-08-22 14:49 UTC, nkkko requested changes
Well written, please read once more and improve where needed. Implement the full checklist. Add at least one definition, author, etc. Please follow the instructions in the readme.

2024-08-22 14:49 UTC, nkkko commented on articles/20240821_oss_model.md
> +description: "Read along as we discuss common failiures in OSS models, and how to plan one which is perfect for your startup."
Improve this please

2024-08-22 14:49 UTC, nkkko commented on articles/20240821_oss_model.md
> +The very first open-source release of CockroachDB was done under the Apache 2.0 License, after which it gained extreme adoption and huge people/community support. However, CockroachDB faced abuse by
do the interlinking from our sitemaps, at least 3 pages, consider adding a new definition realted to the topic: oss licence or similar

2024-08-22 14:54 UTC, hunxjunedo commented
@nkkko one more thing, is there a need to add illustrations ? If so, then I need on design briefing (font, colors etc. if it's specific)

2024-08-23 17:28 UTC, hunxjunedo commented
@nkkko I've applied the changes you suggested, let me know if there's anything else to change.

2024-09-01 22:41 UTC, nkkko requested changes
Proofreading: There are some minor grammatical and spelling errors throughout the text that should be corrected (e.g., "failiures" in the description should be "failures").

Structure: The article could benefit from a more clearly defined structure with subheadings for each main point to improve readability.

Depth: Some sections, particularly the case studies, could be expanded to provide more detailed information and analysis.

Solutions: The "A good OSS Model" section could be expanded to provide more concrete strategies and examples of successful implementations.

Consistency: Ensure consistent formatting throughout the article, especially in the use of bold and italics.

Engagement: Consider adding more engaging elements like pull quotes, infographics, or bullet points to break up the text and highlight key information.

Conclusion: The "Final Thoughts" section could be strengthened to provide a more impactful conclusion that ties together the main points of the article.

Audience consideration: Clarify the target audience and adjust the tone and content accordingly.

2024-09-01 22:41 UTC, nkkko commented on articles/20240821_oss_model.md
> +[Read More: Building a Successful Open Source Project](https://www.daytona.io/dotfiles/building-a-successful-open-source-project)
please fix all of the read more links, all links need to be inline with text, so link appropriate keywords in the text.

2024-09-03 17:34 UTC, hunxjunedo commented
@nkkko applied the requested changes. Please review.

2024-11-20 21:34 UTC, mojafa commented
@hunxjunedo I like how you've incorporated the requests, like pull quotes, and bullet points. Please implement the full checklist. Add images where possible.

@nkkko Reckon there's need for images or inforgraphics on this? This article is well articulated and has data like MySQL vs MongoDB.

2024-11-21 09:44 UTC, merged

2024-11-21 09:53 UTC, nkkko commented
Thanks @hunxjunedo for your work!

You can showcase your contribution on your GitHub profile: https://github.com/daytonaio/content/blob/main/CONTRIBUTING.md#showcase-your-contributions