Feat: How to contribute devcontainer.json to repo
daytonaio/content pull request #42
Opened 2024-08-21 04:16 UTC by itsdheerajdp

/claim #35
Fixes: #35 

## Writer's Checklist

- [ ] **Follow Writing Structure**
  - [ ] I have used more than two H2 subtitles to organize content.
  - [ ] Include an introduction with at least two paragraphs before the first H2 section.
  - [ ] Use bold, italic, underline, notes, quotes, TLDRs, and key points as needed.
  - [ ] Include `code elements` where appropriate.
  - [ ] Write the article in Markdown format.

- [ ] **Fact-Check**
  - [ ] I have verified all facts and data points included in the article.

- [ ] **Assets**
  - [ ] Save images in the `/assets` folder.
  - [ ] Follow naming conventions: `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.

- [ ] **Interlinking**
  - [ ] Use `CTRL+F` to search for relevant keywords on:
    - [Daytona Dotfiles Sitemap](https://www.daytona.io/sitemap-dotfiles.xml)
    - [Daytona Definitions Sitemap](https://www.daytona.io/sitemap-definitions.xml)
  - [ ] Interlink keywords using the appropriate URLs.

- [ ] **Glossary/Definitions**
  - [ ] Identify and mark new terms that could be added to the Definitions page.

- [ ] **Review and Edit**
  - [ ] Read the article out loud to catch any awkward phrasing.
  - [ ] Run the draft through [Grammarly](https://grammarly.com) or a similar tool to correct grammar and spelling errors.
  - [ ] Double-check adherence to the style guide and repository guidelines.

2024-08-22 16:07 UTC, nkkko requested changes
remove the other article from this PR
have you tested the devcontainer locally with VS Code and Daytona?
have you opened PR on groq repo to contribute devcontainer?
please read the readme and follow the checklist if you fail to follow the checklist I would be forced to close the PR (for example you have selected that you have put imgs int oassets and that you have done interlinking, not true)

thanks!

2024-08-23 05:01 UTC, itsdheerajdp commented
@nkkko  I made the requested changes. Kindly check it out...

2024-12-04 23:57 UTC, mojafa commented
@itsdheerajdp I'll review this PR after your other PR is merged. I've just requested for review

2024-12-05 07:10 UTC, itsdheerajdp commented
> @itsdheerajdp I'll review this PR after your other PR is merged/closed. I've just requested for review

This PR is updated as requested long before. Try to review it

2024-12-09 08:02 UTC, mojafa commented
@itsdheerajdp you didnt open a PR on groq repo to contribute devcontainer.

Again, please read the issue #35 
![Screenshot 2024-12-09 at 11 00 48](https://github.com/user-attachments/assets/a3001951-c734-4a43-8c48-b817be200c31)

2024-12-30 12:01 UTC, mojafa commented
@dheerajsingh89 hope you're well. Your article guides users on how to create and contribute a `devcontainer.json` file to the Groq API Cookbook repo, but misses to meet the issue requirements. You need to open a PR on [the](https://github.com/groq/groq-api-cookbook/) with this article. Please refer to the issue again: https://github.com/daytonaio/content/issues/35

2025-01-31 12:15 UTC, mojafa commented
@dheerajsingh89 Thanks for your contribution and discussion on this issue! We're doing some cleanup to keep the repo focused, and we've closed the issue this PR addresses for now. Appreciate your support! 🙏

2025-01-31 12:15 UTC, closed without merging