added News article on v0.25.0
daytonaio/content pull request #60
Opened 2024-08-21 20:39 UTC by DevGajjar28

# Pull Request Template
This PR addresses issue: #55 
/claim #55
/closes #55 

## Writer's Checklist

- [x] **Follow Writing Structure**
  - [ ] I have used more than two H2 subtitles to organize content.
  - [ ] Include an introduction with at least two paragraphs before the first H2 section.
  - [ ] Use bold, italic, underline, notes, quotes, TLDRs, and key points as needed.
  - [ ] Include `code elements` where appropriate.
  - [ ] Write the article in Markdown format.

- [x] **Fact-Check**
  - [ ] I have verified all facts and data points included in the article.

- [x] **Assets**
  - [ ] Save images in the `/assets` folder.
  - [ ] Follow naming conventions: `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.

- [x] **Interlinking**
  - [ ] Use `CTRL+F` to search for relevant keywords on:
    - [Daytona Dotfiles Sitemap](https://www.daytona.io/sitemap-dotfiles.xml)
    - [Daytona Definitions Sitemap](https://www.daytona.io/sitemap-definitions.xml)
  - [ ] Interlink keywords using the appropriate URLs.

- [x] **Glossary/Definitions**
  - [ ] Identify and mark new terms that could be added to the Definitions page.

- [x] **Review and Edit**
  - [ ] Read the article out loud to catch any awkward phrasing.
  - [ ] Run the draft through [Grammarly](https://grammarly.com) or a similar tool to correct grammar and spelling errors.
  - [ ] Double-check adherence to the style guide and repository guidelines.

2024-08-22 10:09 UTC, nkkko requested changes

2024-08-22 10:09 UTC, nkkko commented on articles/20240822_v0.24.0_news.md
> +title: "Daytona v0.24.0"
Please invest more effort to double check everything, you are mixing version numbers
Also please read the issue, this needs to be a fluently written article.

2024-08-22 10:09 UTC, nkkko commented on articles/20240822_v0.24.0_news.md
> +# Daytona v0.24.0 Release Summary
Please tell me if I need to update the task if it was confusing, the idea is to cover the office hours as an article and not version, we have https://www.daytona.io/changelog for this

2024-08-22 10:09 UTC, nkkko commented on articles/20240822_v0.24.0_news.md
> +**Watch the Full Office Hours Recap on YouTube:** [Daytona Office Hours #7](https://www.youtube.com/watch?v=nVQWa4jmwLc&t=622s)
Video can be added at the bottom

2024-08-22 10:09 UTC, nkkko commented on articles/20240822_v0.24.0_news.md
> +## Overview
do not use this type of short headings that don't add value

2024-08-22 10:09 UTC, nkkko commented on articles/20240822_v0.24.0_news.md
> +The Daytona Office Hours #7 introduced several updates in the v0.25. This release focuses on enhancing user experience, improving project management, and extending compatibility with additional Git p
DOH didn't introduce updates, that was done before, but DOH serves to showcase and explain to the community what was done over the last week, sometimes we even don't have new version in the meantime

2024-08-22 10:09 UTC, nkkko commented on articles/20240822_v0.24.0_news.md
> +
You have misunderstood the task so listing features like in the release dosnt make sense

2024-08-22 10:11 UTC, nkkko commented
Also, you have submitted two articles for this task, remove the one that shouldn't be here. Thanks. Please implement the checklist and DCO.

2024-09-01 22:31 UTC, nkkko commented
@DevGajjar28 when will you implement the comments?

2024-11-20 21:36 UTC, mojafa commented
@nkkko should we close this PR?

2024-12-08 18:15 UTC, mojafa commented
This issue has been closed already: https://github.com/daytonaio/content/issues/55

2024-12-08 18:15 UTC, closed without merging