Daytona Office Hours #9 - Pre-Builds Demo & Latest Fixes!
daytonaio/content pull request #70
Opened 2024-08-25 03:39 UTC by Amr2812

## Writer's Checklist

### Writing Structure
- [ x] Use short sentences and paragraphs, and include bucket brigades.
- [ x] Include more than two descriptive H2 headings to organize content.
- [ x] Capitalize headings according to the AP Stylebook ([use this tool](https://capitalizemytitle.com/style/AP/))
- [ x] Include an introduction with at least two paragraphs before the first H2 section.
- [ x] Use appropriate formatting (bold, italic, underline), notes, quotes, TLDRs, and key points.
- [ x] Incorporate `code elements` and `Markdown format` where appropriate.
- [ x] Ensure at least one visual element per “screen” of the article (screenshots, diagrams, tables, graphs, lists, sidenotes, blockquotes).

### Fact-Checking
- [ x] Verify all facts and data points included in the article.

### Asset Management
- [ x] Save images in the `/assets` folder.
- [ x] Follow naming conventions: `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.
- [ ] (Optional) Create a GitHub repo for the code referenced in the article and share it.
- [ ] (Optional) Include a link to this Loom video in the PR comments.

### Interlinking
- [ x] Use `CTRL+F` to search for relevant keywords in:
    - [Daytona Dotfiles Sitemap](https://www.daytona.io/sitemap-dotfiles.xml)
    - [Daytona Definitions Sitemap](https://www.daytona.io/sitemap-definitions.xml)
- [ x] Interlink keywords using the appropriate URLs.

### Glossary/Definitions
- [ ] Create new definition in `/defitnitions` folder.

### Review and Edit
- [ x] Ensure articles address the needs of the target audience and their search intent.
- [ x] Read the article out loud to catch any awkward phrasing.
- [ x] Run the draft through [Grammarly](https://grammarly.com) or a similar grammar tool.
- [ x] Double-check adherence to the style guide and repository guidelines.
- [ x] Use the name of the article for the title of the PR.

2024-09-01 22:23 UTC, nkkko commented on articles/YYYYMMDD_article_template.md
remove this from commit

2024-09-01 22:25 UTC, nkkko requested changes

2024-09-01 22:25 UTC, nkkko commented on authors/name_surname.md
remove this from commit

2024-09-01 22:25 UTC, nkkko commented on articles/2024822_Daytona_Office_Hours_#9.md
> +Daytona-Office-Hours-%239
?

2024-09-01 22:25 UTC, nkkko commented on articles/2024822_Daytona_Office_Hours_#9.md
> +- **Pre-Builds demo**
extend each point just a little bit, see other tldr on the blog

2024-09-01 22:25 UTC, nkkko commented on articles/2024822_Daytona_Office_Hours_#9.md
> +A couple of weeks back we introduced a major feature called [Project Configs](https://github.com/daytonaio/daytona/pull/789). They allow users to define project configurations in advance and use them
too big paragraph make it more readable

2024-09-01 22:25 UTC, nkkko commented on articles/2024822_Daytona_Office_Hours_#9.md
> +Prebuilds are a way to speed up development by setting a project configuration to listen to changes in the underlying repository and run a build whenever necessary to ensure that once the user wants
too big paragraph make it more readable, remove:  In the office hours video, we presented a demo of creating and managing pre-builds.

2024-09-01 22:25 UTC, nkkko commented on articles/2024822_Daytona_Office_Hours_#9.md
> +Furthermore, there are various minor fixes and optimizations that are going to be in the next release. There are some other open pull requests that we are not sure if they are going to be merged righ
remove if it is no value

2024-09-01 22:25 UTC, nkkko commented on articles/2024822_Daytona_Office_Hours_#9.md
> +We finalized this episode by motivating users to submit issues if they encountered any and to contribute to Daytona open-source to win bounties. If you have any questions, ask us at our [community sl
this should be a blog article (news) do not reference episode

2024-09-09 07:37 UTC, Amr2812 commented
@nkkko I requested a review last week.

2024-09-10 09:15 UTC, merged

2024-09-10 09:16 UTC, nkkko commented
Btw @Amr2812 you should be able to see your badge tomorrow here: 
<p>
  <img src="https://api.vaunt.dev/v1/github/entities/Amr2812/achievements?format=svg&limit=3" width="400" />
</p>