20240826_CDEs Recognized in Gartner Hype Cycle for 3rd Year
daytonaio/content pull request #78
Opened 2024-08-26 06:17 UTC by luthfi975

/claim #31
Fixes #31 

## Writer's Checklist

### Writing Structure
- [ ] Use short sentences and paragraphs, and include bucket brigades.
- [ ] Include more than two descriptive H2 headings to organize content.
- [ ] Capitalize headings according to the AP Stylebook ([use this tool](https://capitalizemytitle.com/style/AP/))
- [ ] Include an introduction with at least two paragraphs before the first H2 section.
- [ ] Use appropriate formatting (bold, italic, underline), notes, quotes, TLDRs, and key points.
- [ ] Incorporate `code elements` and `Markdown format` where appropriate.
- [ ] Ensure at least one visual element per “screen” of the article (screenshots, diagrams, tables, graphs, lists, sidenotes, blockquotes).

### Fact-Checking
- [ ] Verify all facts and data points included in the article.

### Asset Management
- [ ] Save images in the `/assets` folder.
- [ ] Follow naming conventions: `YYYYMMDD_title_of_the_article_IMG_NAME_NO.png`.
- [ ] (Optional) Create a GitHub repo for the code referenced in the article and share it.
- [ ] (Optional) Include a link to this Loom video in the PR comments.

### Interlinking
- [ ] Use `CTRL+F` to search for relevant keywords in:
    - [Daytona Dotfiles Sitemap](https://www.daytona.io/sitemap-dotfiles.xml)
    - [Daytona Definitions Sitemap](https://www.daytona.io/sitemap-definitions.xml)
- [ ] Interlink keywords using the appropriate URLs.

### Glossary/Definitions
- [ ] Create new definition in `/defitnitions` folder.

### Review and Edit
- [ ] Ensure articles address the needs of the target audience and their search intent.
- [ ] Read the article out loud to catch any awkward phrasing.
- [ ] Run the draft through [Grammarly](https://grammarly.com) or a similar grammar tool.
- [ ] Double-check adherence to the style guide and repository guidelines.
- [ ] Use the name of the article for the title of the PR.

2024-09-01 22:47 UTC, nkkko requested changes
Provide a brief explanation of Gartner's Hype Cycle for readers who may be unfamiliar with it. Enhance the conclusion with more specific recommendations for CTOs and CEOs considering CDE adoption. Add links to our previous posts and reference them properly inside the text.

2024-09-01 22:47 UTC, nkkko commented on articles/20240826_CDEs Recognized in Gartner Hype Cycle for 3rd Year.md
> +| **Title**                                    | **CDEs Recognized in Gartner Hype Cycle for 3rd Year**                                                                |
this is not the format of the template

2024-09-01 22:47 UTC, nkkko commented on articles/20240826_CDEs Recognized in Gartner Hype Cycle for 3rd Year.md
> +### **Best Practices for Implementing CDEs**
no bold in headings, please check linter

2024-09-01 22:47 UTC, nkkko commented on articles/20240826_CDEs Recognized in Gartner Hype Cycle for 3rd Year.md
> +“Daytona was founded specifically to leverage our deep experience building cloud-based coding platforms and take the developer experience to a whole new level. CDEs being recognized by Gartner confir
add as quote ">"

2024-09-02 15:12 UTC, luthfi975 commented
> Provide a brief explanation of Gartner's Hype Cycle for readers who may be unfamiliar with it. Enhance the conclusion with more specific recommendations for CTOs and CEOs considering CDE adoption. Add links to our previous posts and reference them properly inside the text.

@nkkko  implemented the changes.

2024-11-21 18:12 UTC, mojafa commented
@luthfi975 I've assigned the issue to you. 

Please:
- Populate author folder and assets
- add some images. The article by Daytona on the Rise of CDEs has some resources.

2024-11-21 18:14 UTC, mojafa commented
@luthfi975  Please check this out: [https://www.gartner.com/en/newsroom/press-releases/2024-08-21-gartner-2024-hype-cycle-for-emerging-technologies-highlights-developer-productivity-total-experience-ai-and-security](url)

2024-11-21 18:15 UTC, mojafa commented
@luthfi975 Equally, please fix the commits, your PR is failing DCO check.

2024-12-04 09:35 UTC, mojafa commented
@luthfi975 any updates?

2024-12-21 19:29 UTC, mojafa commented
@luthfi975 any updates?

2024-12-21 19:29 UTC, mojafa commented
I'll close

2025-01-15 17:04 UTC, nkkko commented
No updates for more than a month, have to close this.

2025-01-15 17:04 UTC, closed without merging